name: promote
on:
  workflow_dispatch:
    inputs:
      core-version:
        description: The PatternFly core version
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      CORE_VERSION: ${{ github.event.inputs.core-version }}
      RELEASE_VERSION: ${{ github.event.inputs.version }}
      GH_TOKEN: ${{ secrets.GH_TOKEN_REDALLEN }}
    steps:
      - name: Check out project
        uses: actions/checkout@v4
        with:
          # Needs to be an admin token to get around branch protection.
          token: ${{ secrets.GH_TOKEN_REDALLEN }}

      - name: Set up and build project
        uses: ./.github/actions/setup-project
        with:
          skip-build-cache: true

      - name: Deploy to NPM and Github
        run: .github/promote.sh
