name: Release
on:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/main.yml

  docs:
    name: Documentation
    uses: ./.github/workflows/documentation.yml
    secrets: inherit

  deploy:
    name: Deploy release
    runs-on: ubuntu-latest
    needs: [ci, docs]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Needs to be an admin token to get around branch protection.
      GH_TOKEN: ${{ secrets.GH_TOKEN_REDALLEN }}
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name: Set up and build project
        uses: ./.github/actions/setup-project
        with:
          skip-build-cache: true

      - name: Deploy to NPM and Github
        run: .github/release.sh
